### ISSUE TITLE
Scroll popup flow discussion

### ISSUE THREAD

**Issue by oleg-baturov** [norestlabs/BrowserQuest#41]
#33 #36 

Need to check scroll popup details when eating item.

**Comment by sunrisepopov** [comment]
Hi guys, regarding #33 integration, I found #36 issue can be reopened possibly.
The `delay` was happening because of API calling time.

- To fix this : I made it like, first emit websocket and call startdust api

behind, if we need to do Marketplace API, we need to call stardust api to get User Tokens.
For this : I need to do call stardust API first and emit websocket event. (with upper fix there must be race problem and I checked this)

This is the problem. And it could be kind of risk if we keep this happening.
I want you to join us @gedanziger , @sos0 , @oleg-baturov , @Eskew

**Comment by sunrisepopov** [comment]
For now, I have one solution

- Save User Owned Tokens in LocalStorage
- When User earn item, send websocket with new token info
- UI shows Scroll Popup, and Popup shows marketplace API with stored Tokens and new token.
- Backend call Stardust API to mint token. And emit another socket event for suceed.
- Frontend accept that event and update LocalStorage with new token.

The above step will work without any crash on #36

**Comment by oleg-baturov** [comment]
good. it will work.
:+1:  :100:  :1st_place_medal:
